CREATE TABLE IF NOT EXISTS Users (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	login TEXT NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	photo BLOB
);

CREATE TABLE IF NOT EXISTS Tags (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Ingredients (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Recipes (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	name TEXT NOT NULL UNIQUE,
	rating INTEGER NOT NULL,
	cooking_time INTEGER NOT NULL,
	photo BLOB,
	cooking_method TEXT NOT NULL,
	FOREIGN KEY(user_id) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS RecipeTags (
	recipe_id INTEGER NOT NULL, 
	tag_id INTEGER NOT NULL,
	FOREIGN KEY(recipe_id) REFERENCES Recipes(id),
	FOREIGN KEY(tag_id) REFERENCES Tags(id)
);

CREATE TABLE IF NOT EXISTS RecipeIngredients (
	recipe_id INTEGER NOT NULL, 
	ingredient_id INTEGER NOT NULL,
	FOREIGN KEY(recipe_id) REFERENCES Recipes(id),
	FOREIGN KEY(ingredient_id) REFERENCES Ingredients(id)
);

CREATE TABLE IF NOT EXISTS ShoppingList (
	user_id INTEGER NOT NULL, 
	ingredient_id INTEGER NOT NULL, 
	is_bought INTEGER NOT NULL CHECK(is_bought IN (0,1)),
	FOREIGN KEY(user_id) REFERENCES Users(id),
	FOREIGN KEY(ingredient_id) REFERENCES Ingredients(id)
);